# Generated by savvy: do not edit by hand
#
# Note:
#   This wrapper file is named as `000-wrappers.R` so that this file is loaded
#   first, which allows users to override the functions defined here (e.g., a
#   print() method for an enum).

#' @useDynLib balancing, .registration = TRUE
#' @keywords internal
NULL

# Check class and extract the external pointer embedded in the environment
.savvy_extract_ptr <- function(e, class) {
  if(is.null(e)) {
    return(NULL)
  }

  if(inherits(e, class)) {
    e$.ptr
  } else {
    msg <- paste0("Expected ", class, ", got ", class(e)[1])
    stop(msg, call. = FALSE)
  }
}

# Prohibit modifying environments

#' @export
`$<-.savvy_balancing__sealed` <- function(x, name, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' @export
`[[<-.savvy_balancing__sealed` <- function(x, i, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' Solve a discrete (binary or categorical) entropy balancing problem.
#'
#' @export
`solve_entropy` <- function(`covs`, `group_idx`, `targets`, `base_weights`, `s_weights`, `tols`, `n_eff`, `options`) {
  .Call(savvy_solve_entropy__impl, `covs`, `group_idx`, `targets`, `base_weights`, `s_weights`, `tols`, `n_eff`, `options`)
}

#' Solve a continuous-exposure entropy balancing problem over the whole sample.
#'
#' @export
`solve_entropy_cont` <- function(`covs`, `targets`, `tols`, `dist_ind`, `base_weights`, `s_weights`, `n_eff`, `options`) {
  .Call(savvy_solve_entropy_cont__impl, `covs`, `targets`, `tols`, `dist_ind`, `base_weights`, `s_weights`, `n_eff`, `options`)
}

#' Report the parallel resources the Rust core observes.
#'
#' @returns A list with two elements: `available`, the integer thread count, and
#'   `cap_source`, a string naming the constraint that set it (`"system"` or
#'   `"OMP_THREAD_LIMIT"`).
#' @export
`thread_info` <- function() {
  .Call(savvy_thread_info__impl)
}


