# Generated by savvy: do not edit by hand
#
# Note:
#   This wrapper file is named as `000-wrappers.R` so that this file is loaded
#   first, which allows users to override the functions defined here (e.g., a
#   print() method for an enum).

#' @useDynLib balancing, .registration = TRUE
#' @keywords internal
NULL

# Check class and extract the external pointer embedded in the environment
.savvy_extract_ptr <- function(e, class) {
  if(is.null(e)) {
    return(NULL)
  }

  if(inherits(e, class)) {
    e$.ptr
  } else {
    msg <- paste0("Expected ", class, ", got ", class(e)[1])
    stop(msg, call. = FALSE)
  }
}

# Prohibit modifying environments

#' @export
`$<-.savvy_balancing__sealed` <- function(x, name, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' @export
`[[<-.savvy_balancing__sealed` <- function(x, i, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' Re-evaluate the binary just-identified covariate balancing propensity score
#' estimating functions at a set of coefficients.
#'
#' Given the solved coefficients in `coefs` and the original solve inputs,
#' returns the `n` by `p` per-unit estimating functions at those parameters:
#' column `j` is `s_i c_i(beta) x_ij`, the balancing factor times the model
#' covariate. It supports a finite-difference check of the stored Jacobian
#' without reimplementing the balancing-factor math in R.
#'
#' Internal solver entry point, called from the R layer rather than by users, so
#' it is not exported. `@noRd` keeps it out of the reference and out of
#' NAMESPACE, and survives wrapper regeneration because savvy copies these doc
#' lines into the generated wrapper.
#' @noRd
`eval_psi_cbps` <- function(`coefs`, `covs`, `treat`, `s_weights`, `estimand`, `link`) {
  .Call(savvy_eval_psi_cbps__impl, `coefs`, `covs`, `treat`, `s_weights`, `estimand`, `link`)
}

#' Re-evaluate the discrete entropy estimating functions at a set of duals.
#'
#' Given the solved duals in `coefs` (`p` per group, stacked in group order) and
#' the original solve inputs, returns the `n` by `P` per-unit estimating
#' functions at those parameters, with the same per-group renormalization
#' `esteq_scale` the solve output carried. It supports a finite-difference check
#' of the stored Jacobian without reimplementing the tilt math in R.
#'
#' Internal solver entry point, called from the R layer rather than by users, so
#' it is not exported. `@noRd` keeps it out of the reference and out of
#' NAMESPACE, and survives wrapper regeneration because savvy copies these doc
#' lines into the generated wrapper.
#' @noRd
`eval_psi_entropy` <- function(`coefs`, `covs`, `group_idx`, `targets`, `base_weights`, `s_weights`, `n_eff`, `esteq_scale`) {
  .Call(savvy_eval_psi_entropy__impl, `coefs`, `covs`, `group_idx`, `targets`, `base_weights`, `s_weights`, `n_eff`, `esteq_scale`)
}

#' Re-evaluate the continuous entropy estimating functions at a set of duals.
#'
#' A continuous exposure is the single-group case of the same tilt, so `coefs`
#' is the one dual block of length `p` the solve returned and `esteq_scale` the
#' single renormalization the reported weights carry. Given those and the
#' original solve inputs, returns the `n` by `p` per-unit estimating functions at
#' those parameters, at the scale `solve_entropy_cont` reports. It supports a
#' finite-difference check of the stored Jacobian without reimplementing the
#' tilt math in R. The tolerances and the marginal-column indicator shape only
#' the penalty the solve minimizes, so the re-evaluation does not take them.
#'
#' Internal solver entry point, called from the R layer rather than by users, so
#' it is not exported. `@noRd` keeps it out of the reference and out of
#' NAMESPACE, and survives wrapper regeneration because savvy copies these doc
#' lines into the generated wrapper.
#' @noRd
`eval_psi_entropy_cont` <- function(`coefs`, `covs`, `targets`, `base_weights`, `s_weights`, `n_eff`, `esteq_scale`) {
  .Call(savvy_eval_psi_entropy_cont__impl, `coefs`, `covs`, `targets`, `base_weights`, `s_weights`, `n_eff`, `esteq_scale`)
}

#' Re-evaluate the inverse probability tilting estimating functions at a set of
#' coefficients.
#'
#' Given the solved coefficients in `coefs` (`p` per block, stacked in block
#' order) and the original solve inputs, returns the `n` by `P` per-unit
#' estimating functions at those parameters. `treat_idx` holds the zero-based
#' level of each unit and `focal` the focal level index the focal estimands use.
#' The binary and categorical fits share this entrypoint. It supports a
#' finite-difference check of the stored Jacobian without reimplementing the
#' tilt math in R.
#'
#' Internal solver entry point, called from the R layer rather than by users, so
#' it is not exported. `@noRd` keeps it out of the reference and out of
#' NAMESPACE, and survives wrapper regeneration because savvy copies these doc
#' lines into the generated wrapper.
#' @noRd
`eval_psi_ipt` <- function(`coefs`, `covs`, `treat_idx`, `focal`, `s_weights`, `estimand`, `link`) {
  .Call(savvy_eval_psi_ipt__impl, `coefs`, `covs`, `treat_idx`, `focal`, `s_weights`, `estimand`, `link`)
}

#' Re-evaluate the binary just-identified covariate balancing propensity score
#' weights at a set of coefficients.
#'
#' Given the solved coefficients in `coefs` and the original solve inputs,
#' returns the length-`n` weight vector at those parameters: the estimand's
#' weight function evaluated at the modeled propensity and the unit's treatment
#' indicator. It supports a sandwich variance that treats the weights as a
#' function of the coefficients without reimplementing the propensity math in R.
#'
#' Internal solver entry point, called from the R layer rather than by users, so
#' it is not exported. `@noRd` keeps it out of the reference and out of
#' NAMESPACE, and survives wrapper regeneration because savvy copies these doc
#' lines into the generated wrapper.
#' @noRd
`eval_weights_cbps` <- function(`coefs`, `covs`, `treat`, `s_weights`, `estimand`, `link`) {
  .Call(savvy_eval_weights_cbps__impl, `coefs`, `covs`, `treat`, `s_weights`, `estimand`, `link`)
}

#' Re-evaluate the discrete entropy balancing weights at a set of duals.
#'
#' Given the solved duals in `coefs` (`p` per group, stacked in group order) and
#' the original solve inputs, returns the length-`n` weight vector at those
#' parameters, with the same per-group renormalization `esteq_scale` the solve
#' output carried. Units the solve leaves out, marked by a negative
#' `group_idx`, carry zero. It supports a sandwich variance that treats the
#' weights as a function of the duals without reimplementing the tilt math in R.
#'
#' Internal solver entry point, called from the R layer rather than by users, so
#' it is not exported. `@noRd` keeps it out of the reference and out of
#' NAMESPACE, and survives wrapper regeneration because savvy copies these doc
#' lines into the generated wrapper.
#' @noRd
`eval_weights_entropy` <- function(`coefs`, `covs`, `group_idx`, `targets`, `base_weights`, `s_weights`, `n_eff`, `esteq_scale`) {
  .Call(savvy_eval_weights_entropy__impl, `coefs`, `covs`, `group_idx`, `targets`, `base_weights`, `s_weights`, `n_eff`, `esteq_scale`)
}

#' Re-evaluate the continuous entropy balancing weights at a set of duals.
#'
#' A continuous exposure is the single-group case of the same tilt, so `coefs`
#' is the one dual block of length `p` the solve returned and `esteq_scale` the
#' single renormalization the reported weights carry. Given those and the
#' original solve inputs, returns the length-`n` weight vector at those
#' parameters, at the scale `solve_entropy_cont` reports. It supports a sandwich
#' variance that treats the weights as a function of the duals without
#' reimplementing the tilt math in R.
#'
#' Internal solver entry point, called from the R layer rather than by users, so
#' it is not exported. `@noRd` keeps it out of the reference and out of
#' NAMESPACE, and survives wrapper regeneration because savvy copies these doc
#' lines into the generated wrapper.
#' @noRd
`eval_weights_entropy_cont` <- function(`coefs`, `covs`, `targets`, `base_weights`, `s_weights`, `n_eff`, `esteq_scale`) {
  .Call(savvy_eval_weights_entropy_cont__impl, `coefs`, `covs`, `targets`, `base_weights`, `s_weights`, `n_eff`, `esteq_scale`)
}

#' Re-evaluate the inverse probability tilting weights at a set of
#' coefficients.
#'
#' Given the solved coefficients in `coefs` (`p` per block, stacked in block
#' order) and the original solve inputs, returns the length-`n` weight vector at
#' those parameters. `treat_idx` holds the zero-based level of each unit and
#' `focal` the focal level index the focal estimands use, whose units carry
#' weight one. The binary and categorical fits share this entrypoint. It
#' supports a sandwich variance that treats the weights as a function of the
#' coefficients without reimplementing the tilt math in R.
#'
#' Internal solver entry point, called from the R layer rather than by users, so
#' it is not exported. `@noRd` keeps it out of the reference and out of
#' NAMESPACE, and survives wrapper regeneration because savvy copies these doc
#' lines into the generated wrapper.
#' @noRd
`eval_weights_ipt` <- function(`coefs`, `covs`, `treat_idx`, `focal`, `s_weights`, `estimand`, `link`) {
  .Call(savvy_eval_weights_ipt__impl, `coefs`, `covs`, `treat_idx`, `focal`, `s_weights`, `estimand`, `link`)
}

#' Build a kernel matrix for the covariates.
#'
#' `kernel` names the kernel; `bw_scale` scales the median bandwidth;
#' `smoothness` is the Matern smoothness; `t_proj` is the column-major `p` by
#' `n_draws` t-kernel projection matrix, empty for the other kernels; `s_weights`
#' standardize the covariates; `discarded` marks units excluded from the bandwidth
#' median, empty to discard none. The result is a column-major `n` by `n` symmetric
#' matrix. This entry point is mandated by the boundary contract and is available
#' for building a kernel matrix directly, for diagnostics. The fit path does not
#' call it: the solve entry points build the kernel internally, so the `n` by `n`
#' matrix never crosses the boundary during a fit.
#'
#' Internal solver entry point, called from the R layer rather than by users, so
#' it is not exported. `@noRd` keeps it out of the reference and out of
#' NAMESPACE, and survives wrapper regeneration because savvy copies these doc
#' lines into the generated wrapper.
#' @noRd
`kernel_matrix` <- function(`covs`, `kernel`, `bw_scale`, `smoothness`, `t_proj`, `s_weights`, `discarded`, `options`) {
  .Call(savvy_kernel_matrix__impl, `covs`, `kernel`, `bw_scale`, `smoothness`, `t_proj`, `s_weights`, `discarded`, `options`)
}

#' Solve a binary covariate balancing propensity score problem.
#'
#' `covs_mod` is the propensity-model design and `covs_bal` the balance design;
#' for the just-identified form they must have the same shape. `treat` holds the
#' zero/one treatment indicator; `estimand` is one of `ate`, `att`, `atc`, or
#' `ato`; `link` is the propensity link. `over` selects the over-identified GMM
#' criterion, and `twostep` its two-step weighting matrix.
#'
#' Internal solver entry point, called from the R layer rather than by users, so
#' it is not exported. `@noRd` keeps it out of the reference and out of
#' NAMESPACE, and survives wrapper regeneration because savvy copies these doc
#' lines into the generated wrapper.
#' @noRd
`solve_cbps` <- function(`covs_mod`, `covs_bal`, `treat`, `s_weights`, `estimand`, `link`, `over`, `twostep`, `options`) {
  .Call(savvy_solve_cbps__impl, `covs_mod`, `covs_bal`, `treat`, `s_weights`, `estimand`, `link`, `over`, `twostep`, `options`)
}

#' Solve a continuous-exposure covariate balancing propensity score problem.
#'
#' `expo` holds the continuous exposure of each unit. The continuous form
#' targets the average treatment effect and supplies no estimating equations.
#'
#' Internal solver entry point, called from the R layer rather than by users, so
#' it is not exported. `@noRd` keeps it out of the reference and out of
#' NAMESPACE, and survives wrapper regeneration because savvy copies these doc
#' lines into the generated wrapper.
#' @noRd
`solve_cbps_cont` <- function(`covs`, `expo`, `s_weights`, `options`) {
  .Call(savvy_solve_cbps_cont__impl, `covs`, `expo`, `s_weights`, `options`)
}

#' Solve a categorical covariate balancing propensity score problem.
#'
#' `treat_idx` holds the zero-based level of each unit; `focal` is the focal
#' level index used by `att` and ignored by `ate`. The categorical form is
#' always just-identified.
#'
#' Internal solver entry point, called from the R layer rather than by users, so
#' it is not exported. `@noRd` keeps it out of the reference and out of
#' NAMESPACE, and survives wrapper regeneration because savvy copies these doc
#' lines into the generated wrapper.
#' @noRd
`solve_cbps_multi` <- function(`covs`, `treat_idx`, `focal`, `s_weights`, `estimand`, `link`, `options`) {
  .Call(savvy_solve_cbps_multi__impl, `covs`, `treat_idx`, `focal`, `s_weights`, `estimand`, `link`, `options`)
}

#' Solve a binary-exposure characteristic function distance balancing problem.
#'
#' `treat` holds the zero/one exposure indicator; `kernel` names the kernel;
#' `bw_scale` scales the median bandwidth; `smoothness` is the Matern smoothness;
#' `t_proj` is the column-major `p` by `n_draws` t-kernel projection matrix, empty
#' for the other kernels; `improved` selects the between-group term of the improved
#' average-treatment-effect variant; `estimand` is one of `ate`, `att`, or `atc`.
#' `moment_covs` are the standardized moment-constraint columns with `targets` and
#' `tols`, both empty when no moment constraints are requested.
#'
#' Internal solver entry point, called from the R layer rather than by users, so
#' it is not exported. `@noRd` keeps it out of the reference and out of
#' NAMESPACE, and survives wrapper regeneration because savvy copies these doc
#' lines into the generated wrapper.
#' @noRd
`solve_cfd` <- function(`covs`, `treat`, `s_weights`, `kernel`, `bw_scale`, `smoothness`, `t_proj`, `improved`, `estimand`, `moment_covs`, `targets`, `tols`, `min_weight`, `weight_penalty`, `options`) {
  .Call(savvy_solve_cfd__impl, `covs`, `treat`, `s_weights`, `kernel`, `bw_scale`, `smoothness`, `t_proj`, `improved`, `estimand`, `moment_covs`, `targets`, `tols`, `min_weight`, `weight_penalty`, `options`)
}

#' Solve a multi-category-exposure characteristic function distance balancing
#' problem.
#'
#' `treat_idx` holds the zero-based level of each unit; `focal` is the focal level
#' index used by `att` and ignored by `ate`; `estimand` is `ate` or `att`. The
#' kernel arguments match [`solve_cfd`].
#'
#' Internal solver entry point, called from the R layer rather than by users, so
#' it is not exported. `@noRd` keeps it out of the reference and out of
#' NAMESPACE, and survives wrapper regeneration because savvy copies these doc
#' lines into the generated wrapper.
#' @noRd
`solve_cfd_multi` <- function(`covs`, `treat_idx`, `focal`, `s_weights`, `kernel`, `bw_scale`, `smoothness`, `t_proj`, `improved`, `estimand`, `moment_covs`, `targets`, `tols`, `min_weight`, `weight_penalty`, `options`) {
  .Call(savvy_solve_cfd_multi__impl, `covs`, `treat_idx`, `focal`, `s_weights`, `kernel`, `bw_scale`, `smoothness`, `t_proj`, `improved`, `estimand`, `moment_covs`, `targets`, `tols`, `min_weight`, `weight_penalty`, `options`)
}

#' Solve a binary-exposure energy balancing problem.
#'
#' `treat` holds the zero/one exposure indicator; `distance` names the covariate
#' distance definition; `estimand` is one of `ate`, `att`, or `atc`; `improved`
#' selects the between-group term of the improved average-treatment-effect
#' variant. `moment_covs` are the standardized moment-constraint columns with
#' `targets` and `tols`, both empty when no moment constraints are requested.
#'
#' Internal solver entry point, called from the R layer rather than by users, so
#' it is not exported. `@noRd` keeps it out of the reference and out of
#' NAMESPACE, and survives wrapper regeneration because savvy copies these doc
#' lines into the generated wrapper.
#' @noRd
`solve_energy` <- function(`covs`, `treat`, `s_weights`, `distance`, `estimand`, `improved`, `moment_covs`, `targets`, `tols`, `min_weight`, `weight_penalty`, `options`) {
  .Call(savvy_solve_energy__impl, `covs`, `treat`, `s_weights`, `distance`, `estimand`, `improved`, `moment_covs`, `targets`, `tols`, `min_weight`, `weight_penalty`, `options`)
}

#' Solve a continuous-exposure energy balancing problem.
#'
#' `treat` holds the continuous exposure. `d_covs` and `d_treat` are the
#' distribution-moment columns for the covariates and the exposure, centered and
#' scaled on the R side, and each is held exactly at a weighted mean of zero.
#' The R side centers them on the base measure, so pinning the rows at zero
#' holds every marginal at its base-measure sample value; `bal_covs` and
#' `bal_tols` are the correlation-constraint covariates and their tolerances.
#' `dimension_adj` weights the covariate energy distance by the dimensionality
#' adjustment.
#'
#' Internal solver entry point, called from the R layer rather than by users, so
#' it is not exported. `@noRd` keeps it out of the reference and out of
#' NAMESPACE, and survives wrapper regeneration because savvy copies these doc
#' lines into the generated wrapper.
#' @noRd
`solve_energy_cont` <- function(`covs`, `treat`, `s_weights`, `distance`, `dimension_adj`, `min_weight`, `weight_penalty`, `d_covs`, `d_treat`, `bal_covs`, `bal_tols`, `options`) {
  .Call(savvy_solve_energy_cont__impl, `covs`, `treat`, `s_weights`, `distance`, `dimension_adj`, `min_weight`, `weight_penalty`, `d_covs`, `d_treat`, `bal_covs`, `bal_tols`, `options`)
}

#' Solve a multi-category-exposure energy balancing problem.
#'
#' `treat_idx` holds the zero-based level of each unit; `focal` is the focal
#' level index used by `att` and ignored by `ate`; `estimand` is `ate` or `att`.
#'
#' Internal solver entry point, called from the R layer rather than by users, so
#' it is not exported. `@noRd` keeps it out of the reference and out of
#' NAMESPACE, and survives wrapper regeneration because savvy copies these doc
#' lines into the generated wrapper.
#' @noRd
`solve_energy_multi` <- function(`covs`, `treat_idx`, `focal`, `s_weights`, `distance`, `estimand`, `improved`, `moment_covs`, `targets`, `tols`, `min_weight`, `weight_penalty`, `options`) {
  .Call(savvy_solve_energy_multi__impl, `covs`, `treat_idx`, `focal`, `s_weights`, `distance`, `estimand`, `improved`, `moment_covs`, `targets`, `tols`, `min_weight`, `weight_penalty`, `options`)
}

#' Solve a discrete (binary or categorical) entropy balancing problem.
#'
#' Internal solver entry point, called from the R layer rather than by users, so
#' it is not exported. `@noRd` keeps it out of the reference and out of
#' NAMESPACE, and survives wrapper regeneration because savvy copies these doc
#' lines into the generated wrapper.
#' @noRd
`solve_entropy` <- function(`covs`, `group_idx`, `targets`, `base_weights`, `s_weights`, `tols`, `n_eff`, `options`) {
  .Call(savvy_solve_entropy__impl, `covs`, `group_idx`, `targets`, `base_weights`, `s_weights`, `tols`, `n_eff`, `options`)
}

#' Solve a continuous-exposure entropy balancing problem over the whole sample.
#'
#' Internal solver entry point, called from the R layer rather than by users, so
#' it is not exported. `@noRd` keeps it out of the reference and out of
#' NAMESPACE, and survives wrapper regeneration because savvy copies these doc
#' lines into the generated wrapper.
#' @noRd
`solve_entropy_cont` <- function(`covs`, `targets`, `tols`, `dist_ind`, `base_weights`, `s_weights`, `n_eff`, `options`) {
  .Call(savvy_solve_entropy_cont__impl, `covs`, `targets`, `tols`, `dist_ind`, `base_weights`, `s_weights`, `n_eff`, `options`)
}

#' Solve a binary inverse probability tilting problem.
#'
#' `treat` holds the zero/one treatment indicator; `estimand` is one of `ate`,
#' `att`, or `atc`, and `link` is the propensity link.
#'
#' Internal solver entry point, called from the R layer rather than by users, so
#' it is not exported. `@noRd` keeps it out of the reference and out of
#' NAMESPACE, and survives wrapper regeneration because savvy copies these doc
#' lines into the generated wrapper.
#' @noRd
`solve_ipt` <- function(`covs`, `treat`, `s_weights`, `estimand`, `link`, `options`) {
  .Call(savvy_solve_ipt__impl, `covs`, `treat`, `s_weights`, `estimand`, `link`, `options`)
}

#' Solve a categorical inverse probability tilting problem.
#'
#' `treat_idx` holds the zero-based level of each unit; `focal` is the focal
#' level index used by `att` and `atc` and ignored by `ate`.
#'
#' Internal solver entry point, called from the R layer rather than by users, so
#' it is not exported. `@noRd` keeps it out of the reference and out of
#' NAMESPACE, and survives wrapper regeneration because savvy copies these doc
#' lines into the generated wrapper.
#' @noRd
`solve_ipt_multi` <- function(`covs`, `treat_idx`, `focal`, `s_weights`, `estimand`, `link`, `options`) {
  .Call(savvy_solve_ipt_multi__impl, `covs`, `treat_idx`, `focal`, `s_weights`, `estimand`, `link`, `options`)
}

#' Solve a binary-exposure stable balancing problem.
#'
#' `treat` holds the zero/one exposure indicator; `estimand` is one of `ate`,
#' `att`, or `atc`; `norm` names the dispersion norm to minimize. `moment_covs`
#' are the standardized balance columns with their `targets` and `tols`, all
#' empty when no balance constraints are requested.
#'
#' Internal solver entry point, called from the R layer rather than by users, so
#' it is not exported. `@noRd` keeps it out of the reference and out of
#' NAMESPACE, and survives wrapper regeneration because savvy copies these doc
#' lines into the generated wrapper.
#' @noRd
`solve_sbw` <- function(`treat`, `s_weights`, `estimand`, `norm`, `moment_covs`, `targets`, `tols`, `min_weight`, `options`) {
  .Call(savvy_solve_sbw__impl, `treat`, `s_weights`, `estimand`, `norm`, `moment_covs`, `targets`, `tols`, `min_weight`, `options`)
}

#' Solve a continuous-exposure stable balancing problem.
#'
#' `treat` holds the continuous exposure; `covs` are the standardized covariate
#' columns held in weighted correlation with the exposure within `tols`; `norm`
#' names the dispersion norm to minimize.
#'
#' Internal solver entry point, called from the R layer rather than by users, so
#' it is not exported. `@noRd` keeps it out of the reference and out of
#' NAMESPACE, and survives wrapper regeneration because savvy copies these doc
#' lines into the generated wrapper.
#' @noRd
`solve_sbw_cont` <- function(`treat`, `covs`, `s_weights`, `norm`, `tols`, `min_weight`, `options`) {
  .Call(savvy_solve_sbw_cont__impl, `treat`, `covs`, `s_weights`, `norm`, `tols`, `min_weight`, `options`)
}

#' Solve a multi-category-exposure stable balancing problem.
#'
#' `treat_idx` holds the zero-based level of each unit; `focal` is the focal
#' level index used by `att` and ignored by `ate`; `estimand` is `ate` or `att`.
#'
#' Internal solver entry point, called from the R layer rather than by users, so
#' it is not exported. `@noRd` keeps it out of the reference and out of
#' NAMESPACE, and survives wrapper regeneration because savvy copies these doc
#' lines into the generated wrapper.
#' @noRd
`solve_sbw_multi` <- function(`treat_idx`, `focal`, `s_weights`, `estimand`, `norm`, `moment_covs`, `targets`, `tols`, `min_weight`, `options`) {
  .Call(savvy_solve_sbw_multi__impl, `treat_idx`, `focal`, `s_weights`, `estimand`, `norm`, `moment_covs`, `targets`, `tols`, `min_weight`, `options`)
}

#' Report the parallel resources the Rust core observes.
#'
#' A list with two elements: `available`, the integer thread count, and
#' `cap_source`, a string naming the constraint that set it (`"system"` or
#' `"OMP_THREAD_LIMIT"`).
#'
#' This is an internal solver entry point, called from the R layer rather than
#' by users, so it is not exported. `@noRd` keeps it out of the reference and
#' out of NAMESPACE; savvy copies these doc lines into the generated wrapper, so
#' the tag survives wrapper regeneration.
#' @noRd
`thread_info` <- function() {
  .Call(savvy_thread_info__impl)
}


